In [106]:
from numpy import random
print(random.randint(1,100))# random integer in the given range
print(random.rand()) #float number 0-1

94
0.08581090722752538


In [107]:
#creating n-dimensional array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[54 37 34]
[[15 93 99 27]
 [23 95 28 13]
 [59 79 49  8]]
[[[34 67]
  [ 1 92]
  [30 12]
  [45 55]]

 [[45 39]
  [31 28]
  [74  9]
  [ 0 10]]

 [[89 61]
  [28 37]
  [93 19]
  [46  5]]]


In [108]:
#creating n-dimensional array with random float values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.09231791147367585
[0.46927918 0.65819636 0.77275803]
[[0.61918775 0.5609031  0.71342997]
 [0.40464122 0.24155315 0.6510851 ]]


In [109]:
a = random.randint(100,size=(3,4)).ravel()
print(a)

[27 72 76 53 53 48  8 36 67 82 98 87]


In [110]:
#single element will be selected
random.choice(a)

36

In [111]:
#for genarating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[4, 5, 5, 4],
       [4, 4, 1, 1],
       [1, 3, 5, 5],
       [5, 4, 3, 5]])

### pandas:
1. Data manipulation,analysis and cleaning
2. Tabular ,Unlabelled

### Creating a DataFrame
1. using 2 dictionaries
2. simple dictionary --> DataFrame
3. Using series 

In [112]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data={"First":dict1,"Second":dict2}
df=pd.DataFrame(data)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [113]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'f':9}
data={"First":dict1,"Second":dict2}
df=pd.DataFrame(data,dtype=np.int32)
df

First  Second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0

In [114]:
#simple dictionary --> DataFrame
d1 = {"name":["preethi","mounika","sumathi"],"address":["hyd","adb","AP"]}
df1 = pd.DataFrame(d1)
df1

name address
0  preethi     hyd
1  mounika     adb
2  sumathi      AP

In [115]:
#using Series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([12.23,23.34,45.3,45.5,67.4,67.78,34.45,23.34,67.4,23])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df1 =pd.DataFrame(data)
df1

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

### Selecting the data from the DataFrame:
1. loc
2. iloc

In [116]:
df1["column2"]

0    12.23
1    23.34
2    45.30
3    45.50
4    67.40
5    67.78
6    34.45
7    23.34
8    67.40
9    23.00
Name: column2, dtype: float64

In [117]:
df1[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    45.30       c
3    45.50       d
4    67.40       e
5    67.78       f
6    34.45       g
7    23.34       h
8    67.40       i
9    23.00       j

In [118]:
#single column
df1.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [119]:
df1.loc[:,["column1","column2"]] # loc[row index,column]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    67.40
5        6    67.78
6        7    34.45
7        8    23.34
8        9    67.40
9       10    23.00

In [120]:
#Extracting multiple column values
df1.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    67.40
5        6    67.78

In [121]:
df1.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [122]:
df1.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retrieving the information of DataFrame

In [123]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [124]:
df1.shape

(10, 3)

In [125]:
df1.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [126]:
df1.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [127]:
df1.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e

In [128]:
df1.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [129]:
df1.tail()

column1  column2 column3
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

In [130]:
df1.tail(2)

column1  column2 column3
8        9     67.4       i
9       10     23.0       j

In [131]:
df1.sample()

column1  column2 column3
8        9     67.4       i

In [132]:
df1.sample(3)

column1  column2 column3
4        5    67.40       e
3        4    45.50       d
0        1    12.23       a

In [133]:
df1.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  40.974000
std     3.02765  20.997852
min     1.00000  12.230000
25%     3.25000  23.340000
50%     5.50000  39.875000
75%     7.75000  61.925000
max    10.00000  67.780000

In [134]:
df1=df1.rename(columns={"column1":"First",
                    "column2":"Second",
                   "column3":"Third"})
df1

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   67.40     e
5      6   67.78     f
6      7   34.45     g
7      8   23.34     h
8      9   67.40     i
9     10   23.00     j